apiVersion: v1
kind: Service
metadata:
  name: vtgate-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    box.com/component: vitess-vtgate-lb
spec:
  type: LoadBalancer
  selector:
    planetscale.com/component: vtgate
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
